name: Deploy RAVOX

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd ${{ secrets.PROJECT_PATH }}

            echo "== Pull Repository =="
            git pull origin main

            echo "== Composer =="
            composer install --no-dev --optimize-autoloader

            echo "== Laravel =="
            php artisan migrate --force
            php artisan optimize:clear
            php artisan optimize

            echo "== Frontend =="
            npm install
            npm run build

            echo "== Permission =="
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            echo "== Restart PHP =="
            sudo systemctl reload php8.4-fpm

            echo "== Done =="